services:
  - type: web
    name: connect-pro-1
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: ./node_modules/.bin/tsx server.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "22"
      - key: PORT
        value: "10000"
      - key: RENDER_EXTERNAL_URL
        value: https://connect-pro-1.onrender.com
